name: Generate Minor Release
on: 
  workflow_dispatch:
jobs: 
  use_api: 
    runs-on: ubuntu-20.04
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api respos/DiegoRenan/message_me/issues
