name: Generate Minor Release
on: 
  workflow_dispatch:
    inputs:
      minor_version:
        required: true
        type: number
jobs: 
  first-job: 
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          ref: main
      - name: List branches
        run: echo "Version ${{ inputs.minor_version }}"
